import { LineEdit, ComboBox } from "std-widgets.slint";

export component MainWindow inherits Window {
    title: "Our-Pipe";
    width: 500px;
    height: 300px;
    background: #372d6b;

    out property <string> url;
    out property <string> file-name;
    out property <string> format;
    out property <string> quality;

    pure callback download-button-clicked();

    HorizontalLayout {
        alignment: LayoutAlignment.center;

        VerticalLayout {
            width: root.width;
            padding: 20px;
            spacing: 17px;
            alignment: LayoutAlignment.start;

            HorizontalLayout {
                Text {
                    text: "URL : ";
                    font-size: 25px;
                }

                input-url := LineEdit {
                    text: url;
                    font-size: 14px;
                }
            }

            HorizontalLayout {
                Text {
                    text: "File Name : ";
                    font-size: 25px;
                }

                input-file-name := LineEdit {
                    text: file-name;
                    font-size: 14px;
                }
            }

            HorizontalLayout {
                Text {
                    text: "Format : ";
                    font-size: 25px;
                }

                input-format := ComboBox {
                    model: ["mp4", "mp3"];
                    current-value: format;
                }
            }

            HorizontalLayout {
                Text {
                    text: "Quality : ";
                    font-size: 25px;
                }

                input-quality := ComboBox {
                    model: ["Best", "High", "Medium", "Low", "Worst"];
                    current-value: quality;
                }
            }

            HorizontalLayout {
                Rectangle {
                    height: 60px;
                    background: #ce5252;
                    border-radius: 15px;

                    Text {
                        text: "Download";
                        font-size: 25px;
                    }

                    TouchArea {
                        mouse-cursor: MouseCursor.pointer;

                        clicked => {
                            root.download-button-clicked();
                        }
                    }
                }
            }
        }
    }
}
